### ISSUE TITLE
Push FoodData Central API v1.0.1

### ISSUE THREAD

**Issue by alexanderilyin** [deep-space-cartel/fooddata-central-client-go#1]
# TODO

- [ ] `pip` Dev Container Feature does not ask to customize `packages` property on start.
- [ ] Disable Docker Scout from automatic scanning.
- [ ] `starship` Dev Container Feature does not work in vanilla Go image as expected.
